name: CI
on:
  push:
    paths:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: sbt
      - name: Setup sbt launcher
        uses: sbt/setup-sbt@v1
      - run: sbt "scalafmtCheck;test"
